/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Portable format for MLIR Playground state.
 */
export interface MLIRPlaygroundState {
  /**
   * The schema version this file follows.
   */
  version: string;
  /**
   * The compiler environment that this file is created with.
   */
  environment?: string;
  /**
   * The initial input at the beginning of the pipeline.
   */
  input?: string;
  /**
   * Information about each stage in the pipeline.
   *
   * @minItems 1
   */
  stages: [
    {
      /**
       * The name of the preset being used for this stage.
       */
      preset: string;
      /**
       * The user-editable portion of the argument string that will be used to run the compiled program with.
       */
      arguments: string;
      /**
       * Contents of each of the editors.
       */
      editors: {
        /**
         * Name of this editor tab.
         */
        name: string;
        /**
         * The full contents of this editor
         */
        contents: string;
      }[];
      /**
       * The initial content to fill the output window with.
       */
      output?: string;
    },
    ...{
      /**
       * The name of the preset being used for this stage.
       */
      preset: string;
      /**
       * The user-editable portion of the argument string that will be used to run the compiled program with.
       */
      arguments: string;
      /**
       * Contents of each of the editors.
       */
      editors: {
        /**
         * Name of this editor tab.
         */
        name: string;
        /**
         * The full contents of this editor
         */
        contents: string;
      }[];
      /**
       * The initial content to fill the output window with.
       */
      output?: string;
    }[]
  ];
}
