build-appliance:
	docker build -f appliance.dockerfile -t mlir-playground ..

run-appliance:
	docker run -d -p 3000:3000 mlir-playground

run-appliance-hub:
	docker run -d -p 3000:3000 mlirchina/mlir-playground
