name: Build Website

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: build-site-${{ github.ref }}
  cancel-in-progress: true

env:
  COMMIT_SHA: ${{ github.sha }}
  DOCKER_HUB_NAMESPACE: jackalcooper

jobs:
  build:
    name: Build Entire Website
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        DOCKER_REPO: ["clang-wasm"]

    env:
      DOCKER_REPO: "${{ matrix.DOCKER_REPO }}"
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run wasm setup
        working-directory: ./cpp/
        run: ./build-compiler-in-docker.sh ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ env.COMMIT_SHA }}

      - name: Install npm dependencies
        run: npm install
      
      - name: Run npm build
        run: npm run build
