name: Build Clang WASM image

on:
  workflow_dispatch:
  push:
    branches:
      - "add-actions"

concurrency:
  group: build-img-${{ github.ref }}
  cancel-in-progress: true

env:
  COMMIT_SHA: ${{ github.sha }}
  DOCKER_HUB_NAMESPACE: jackalcooper

jobs:
  build:
    name: Build ${{ matrix.tag-suffix }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        DOCKER_REPO: ["clang-wasm"]

    env:
      DOCKER_REPO: "${{ matrix.DOCKER_REPO }}"

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 7
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ env.COMMIT_SHA }}
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
          cache-to: type=inline
          context: ./cpp/docker
