name: Build and Deploy
# This action will automatically build and deploy to either preview or production.
# If triggered by a pull request, it will deploy a non-production version to Netlify with everything packaged together.
# If triggered by a push to `main`, it will deploy a production version to Cloudflare, with wasm artifacts pushed to B2.

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: build-and-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    env:
      DOCKER_HUB_NAMESPACE: jackalcooper
      DOCKER_REPO: clang-wasm
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      # Build new Docker image if needed
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: |
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
          cache-to: type=inline
          context: ./cpp/docker
      
      # Generate wasm files
      - name: Run wasm setup
        working-directory: ./cpp/
        run: ./build-compiler-in-docker.sh ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ github.sha }}

      - name: Upload artifacts to B2
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./scripts/upload_to_b2.sh mlir-playground ${{ secrets.B2_APPLICATION_KEY_ID }} ${{ secrets.B2_APPLICATION_KEY }} ./public/wasm files
      
      - name: Remove wasm files from production build
        if: ${{ github.ref == 'refs/heads/main' }}
        run: rm -r ./public/wasm

      # Build site
      - name: Install npm dependencies
        run: npm install

      - name: Set build environment
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "PRODUCTION_DOMAIN=playground.mlir-china.org" >> $GITHUB_ENV
          echo "WASM_GEN_PREFIX=https://static.mlir-china.org/file/mlir-playground/files/" >> $GITHUB_ENV
      
      - name: Run npm build
        run: npm run build
      
      - name: Export static website
        run: npx next export
      
      # Push docker image if on `main`
      - name: Push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}d
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
          cache-to: type=inline
          context: ./cpp/docker

      # Deploy site. Netlify for previews, Cloudflare for production.
      - name: Deploy to Netlify
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: './out'
          production-deploy: ${{ github.ref == 'refs/heads/main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deployed ${{ github.ref }} to Netlify"
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Push site to Cloudflare Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: cloudflare/pages-action@v1.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mlir-playground
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
