name: Deploy to Netlify

on:
  workflow_call:
    inputs:
      deploy_message:
        required: true
        type: string

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  COMMIT_SHA: ${{ github.sha }}
  
jobs:
  deploy:
    runs-on: ubuntu-20.04

    env:
      DOCKER_HUB_NAMESPACE: jackalcooper
      DOCKER_REPO: clang-wasm
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run wasm setup
        working-directory: ./cpp/
        run: ./build-compiler-in-docker.sh ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ env.COMMIT_SHA }}

      - name: Install npm dependencies
        run: npm install
      
      - name: Run npm build
        run: npm run build
      
      - name: Export static website
        run: npx next export

      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: './out'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ inputs.deploy_message }}
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
