name: Deploy main branch to production

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: deploy-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-site.yml
    with:
      is_prod: true
