name: Deploy dev branch to production

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: deploy-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Deploy to prod site
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev
      
      - name: Push to production branch (static)
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: static
          FOLDER: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Auto deployment from dev branch at {sha}"
