name: Deploy main branch

on:
  workflow_call:
    inputs:
      is_prod:
        required: true
        type: boolean

concurrency:
  group: deploy-site-${{ github.ref }}-${{ inputs.is_prod }}
  cancel-in-progress: true

env:
  COMMIT_SHA: ${{ github.sha }}
  DOCKER_HUB_NAMESPACE: jackalcooper
  DOCKER_REPO: clang-wasm

jobs:
  deploy:
    name: Deploy to site
    runs-on: ubuntu-20.04

    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
      B2_APP_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
      B2_APP_KEY: ${{ secrets.B2_APPLICATION_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run wasm setup
        working-directory: ./cpp/
        run: ./build-compiler-in-docker.sh ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest

      - name: Upload wasm files to dev
        if: ${{ ! inputs.is_prod }}
        run: ./scripts/upload_wasm_to_b2.sh mlir-playground ${{ secrets.B2_APPLICATION_KEY_ID }} ${{ secrets.B2_APPLICATION_KEY }} ./public/wasm dev
      
      - name: Upload wasm files to prod
        if: ${{ inputs.is_prod }}
        run: ./scripts/upload_wasm_to_b2.sh mlir-playground ${{ secrets.B2_APPLICATION_KEY_ID }} ${{ secrets.B2_APPLICATION_KEY }} ./public/wasm files
      
      - name: Remove wasm files
        run: rm -r public/wasm

      - name: Install npm dependencies
        run: npm install

      - name: Set build environment to staging
        if: ${{ ! inputs.is_prod }}
        run: export APP_ENV=staging
      
      - name: Set build environment to production
        if: ${{ inputs.is_prod }}
        run: export APP_ENV=production
      
      - name: Run npm build
        run: npm run build
      
      - name: Export static website
        run: npx next export
      
      - name: Push to dev branch
        if: ${{ ! inputs.is_prod }}
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dev
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Auto dev deployment from main branch at {sha}"
      
      - name: Push to prod branch
        if: ${{ inputs.is_prod }}
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: static
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Auto prod deployment from main branch at {sha}"
