name: Deploy main branch to dev

on:
  workflow_run:
    workflows: [Build Clang WASM Image]
    types: [completed]
    branches: [main]

concurrency:
  group: deploy-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deploy-site.yml
    with:
      is_prod: false
    secrets: inherit
