name: Release

on:
  workflow_dispatch:

jobs:
  release-mlir-playground:
    runs-on: ubuntu-20.04

    env:
      DOCKER_HUB_NAMESPACE: jackalcooper
      DOCKER_REPO: clang-wasm
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      # Set up environment
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 8

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure Node version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Get the version number to tag with
      - name: Find current version number
        run: echo "NEXT_TAG=mlir-playground-static-$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Ensure current version is not already tagged
        run: test -z $(git tag -l ${{ env.NEXT_TAG }})

      # Prepare website build
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: |
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
          cache-to: type=inline
          context: ./cpp/docker

      # Generate wasm files
      - name: Run wasm setup
        working-directory: ./cpp/
        run: ./build-compiler-in-docker.sh ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ github.sha }}

      # Build site
      - name: Install npm dependencies
        run: npm install

      - name: Set static production build environment
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "PRODUCTION_DOMAIN=playground.mlir-china.org" >> $GITHUB_ENV

      - name: Run npm build
        run: npm run build

      - name: Export static website
        run: npx next export

      - name: Package the mlir-playground static site
        run: |
          STATIC_SITE_PATH=mlir-playground-static.tar.gz
          cd out
          tar cvzf ../${STATIC_SITE_PATH} .
          echo "STATIC_SITE_PATH=${STATIC_SITE_PATH}" >> $GITHUB_ENV

      - name: Release the static site
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.STATIC_SITE_PATH }}
          tag_name: ${{ env.NEXT_TAG }}
          body: "This release contains a static website without any server side logic. Can be hosted using any web server that serves static content."
