name: Release

on:
  workflow_dispatch:

jobs:
  release-mlir-playground:
    runs-on: ubuntu-20.04

    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      # Set up environment
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure Node version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Get the version number to tag with
      - name: Find current version number
        run: echo "NEXT_TAG=mlir-playground-static-$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Ensure current version is not already tagged
        run: test -z $(git tag -l ${{ env.NEXT_TAG }})

      # Generate wasm files
      - name: Run wasm setup
        working-directory: ./cpp/
        run: ./build-compiler-in-docker.sh $(cat clang-wasm-image.txt)

      # Build site
      - name: Install npm dependencies
        run: npm install

      - name: Set static production build environment
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "PRODUCTION_DOMAIN=playground.mlir-china.org" >> $GITHUB_ENV
          echo "SHARE_LINK_GENERATOR=https://playground.mlir-china.org/api/createShareLink" >> $GITHUB_ENV

      - name: Run npm build
        run: npm run build

      - name: Export static website
        run: npx next export

      - name: Package the mlir-playground static site
        run: |
          STATIC_SITE_PATH=mlir-playground-static.tar.gz
          cd out
          tar cvzf ../${STATIC_SITE_PATH} .
          echo "STATIC_SITE_PATH=${STATIC_SITE_PATH}" >> $GITHUB_ENV

      - name: Release the static site
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.STATIC_SITE_PATH }}
          tag_name: ${{ env.NEXT_TAG }}
          body: "This release contains a static website without any server side logic. Can be hosted using any web server that serves static content."
