name: Release

on:
  workflow_dispatch:

jobs:
  release-mlir-playground:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the default branch
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Get a patch release
        run: python .github/scripts/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_RELEASE_TOKEN }}
